import streamlit as st
from auth import handle_oauth_callback, get_auth_url, is_logged_in, logout
from db import upsert_user, save_session, fetch_leaderboard, fetch_user_history, test_connection
from question_gen import get_questions

# ── Page config ──────────────────────────────────────────────
st.set_page_config(
    page_title="Data Engineering Quiz",
    page_icon="🛢️",
    layout="centered",
)

TOPICS = [
    "SQL",
    "Snowflake",
    "dbt",
    "Apache Spark",
    "Databricks",
    "Data Modeling",
    "ELT/ETL",
    "Python",
    "Cloud Storage",
]

DIFFICULTIES = ["Easy", "Medium", "Hard"]

# ── OAuth callback (must run before any UI) ──────────────────
handle_oauth_callback()


# ── Connection check ─────────────────────────────────────────
if "sf_ok" not in st.session_state:
    ok, err = test_connection()
    st.session_state["sf_ok"] = ok
    st.session_state["sf_err"] = err

if not st.session_state["sf_ok"]:
    st.title("🛢️ Data Engineering Quiz")
    st.error("The service is temporarily unavailable. Please try again later.")
    if st.button("Retry"):
        st.session_state.pop("sf_ok", None)
        st.cache_resource.clear()
        st.rerun()
    st.stop()


# ── Sidebar ──────────────────────────────────────────────────
with st.sidebar:
    st.title("🛢️ DE Quiz")
    if is_logged_in():
        user = st.session_state["user"]
        if user.get("picture"):
            st.image(user["picture"], width=48)
        st.write(f"**{user['display_name']}**")
        if not user.get("is_guest"):
            st.caption(user["email"])
        if st.button("Log out"):
            logout()
            st.rerun()
        st.divider()
        nav_options = ["Quiz", "Leaderboard"]
        if not user.get("is_guest"):
            nav_options.insert(1, "My History")
        page = st.radio("Navigate", nav_options)
    else:
        page = "home"


# ── Helper: reset quiz state ─────────────────────────────────
def reset_quiz():
    for key in ["questions", "current_q", "answers", "score",
                "quiz_done", "selected_topics", "difficulty", "num_questions"]:
        st.session_state.pop(key, None)


# ═══════════════════════════════════════════════════════════════
# PAGE: Home / Login
# ═══════════════════════════════════════════════════════════════
if not is_logged_in():
    st.title("🛢️ Data Engineering Quiz")
    st.markdown(
        "Test your knowledge across SQL, Snowflake, dbt, Spark, Databricks, "
        "Data Modeling, ELT/ETL, Python, and Cloud Storage.\n\n"
        "Questions are AI-generated by **Snowflake Cortex** and adapt to your chosen difficulty."
    )
    st.divider()

    auth_url = get_auth_url()
    st.link_button("Sign in with Google", auth_url, type="primary", use_container_width=True)

    st.markdown("**— or —**")

    with st.form("guest_form"):
        guest_name = st.text_input("Play as guest", placeholder="Enter your name")
        submitted = st.form_submit_button("Continue as Guest", use_container_width=True)
        if submitted:
            name = guest_name.strip() or "Guest"
            st.session_state["user"] = {
                "email":        f"guest_{name.lower().replace(' ', '_')}",
                "display_name": name,
                "picture":      "",
                "is_guest":     True,
            }
            st.session_state["user_id"] = None
            st.rerun()

    st.stop()


# ── Ensure registered user is in Snowflake ───────────────────
user = st.session_state["user"]
if "user_id" not in st.session_state:
    if not user.get("is_guest"):
        st.session_state["user_id"] = upsert_user(
            user["email"], user["display_name"], user.get("picture", "")
        )
    else:
        st.session_state["user_id"] = None


# ═══════════════════════════════════════════════════════════════
# PAGE: Quiz
# ═══════════════════════════════════════════════════════════════
if page == "Quiz":

    # ── Setup screen ─────────────────────────────────────────
    if "questions" not in st.session_state:
        st.title("New Quiz")

        selected_topics = st.multiselect(
            "Select topics (pick at least one)",
            TOPICS,
            default=["SQL", "Snowflake"],
        )
        col1, col2 = st.columns(2)
        with col1:
            difficulty = st.selectbox("Difficulty", DIFFICULTIES)
        with col2:
            num_questions = st.selectbox("Number of questions", [10, 20])

        st.divider()
        show_on_leaderboard = st.checkbox(
            "Add my score to the public leaderboard", value=True
        )
        if st.button("Start Quiz 🚀", type="primary", use_container_width=True,
                     disabled=len(selected_topics) == 0):
            with st.spinner("Generating your quiz with Cortex… this may take ~15 seconds on first run."):
                questions = get_questions(selected_topics, difficulty, num_questions)

            if not questions:
                st.error("Could not generate questions. Please try again.")
                st.stop()

            st.session_state.update({
                "questions":          questions,
                "current_q":          0,
                "answers":            {},
                "score":              0,
                "quiz_done":          False,
                "selected_topics":    selected_topics,
                "difficulty":         difficulty,
                "num_questions":      num_questions,
                "show_on_leaderboard": show_on_leaderboard,
            })
            st.rerun()
        st.stop()

    # ── Quiz done — results screen ────────────────────────────
    if st.session_state.get("quiz_done"):
        questions = st.session_state["questions"]
        score     = st.session_state["score"]
        total     = len(questions)
        pct       = round(score / total * 100)

        st.title("Results")
        col1, col2, col3 = st.columns(3)
        col1.metric("Score", f"{score}/{total}")
        col2.metric("Percentage", f"{pct}%")
        col3.metric("Difficulty", st.session_state["difficulty"])

        if pct >= 80:
            st.success("Excellent work! 🏆")
        elif pct >= 60:
            st.info("Good effort! Keep practising. 💪")
        else:
            st.warning("Keep studying — you'll get there! 📚")

        st.divider()
        st.subheader("Review")
        for i, q in enumerate(questions):
            user_ans = st.session_state["answers"].get(i)
            correct  = q["correct_option"]
            icon     = "✅" if user_ans == correct else "❌"
            with st.expander(f"{icon} Q{i+1}: {q['question_text']}"):
                for opt in ["A", "B", "C", "D"]:
                    text = q[f"option_{opt.lower()}"]
                    if opt == correct:
                        st.markdown(f"**{opt}. {text}** ✓")
                    elif opt == user_ans:
                        st.markdown(f"~~{opt}. {text}~~ ✗")
                    else:
                        st.markdown(f"{opt}. {text}")
                st.info(f"**Explanation:** {q['explanation']}")

        st.divider()
        if st.button("Take another quiz", use_container_width=True):
            reset_quiz()
            st.rerun()
        st.stop()

    # ── Active question ───────────────────────────────────────
    questions = st.session_state["questions"]
    idx       = st.session_state["current_q"]
    total     = len(questions)
    q         = questions[idx]

    st.progress(idx / total, text=f"Question {idx+1} of {total}")
    st.subheader(f"Q{idx+1}. {q['question_text']}")

    already_answered = idx in st.session_state["answers"]

    if not already_answered:
        choice = st.radio(
            "Choose your answer:",
            ["A", "B", "C", "D"],
            format_func=lambda x: f"{x}. {q[f'option_{x.lower()}']}",
            key=f"radio_{idx}",
        )
        if st.button("Submit", type="primary"):
            st.session_state["answers"][idx] = choice
            if choice == q["correct_option"]:
                st.session_state["score"] += 1
            st.rerun()
    else:
        user_ans = st.session_state["answers"][idx]
        correct  = q["correct_option"]
        for opt in ["A", "B", "C", "D"]:
            text = q[f"option_{opt.lower()}"]
            if opt == correct:
                st.success(f"**{opt}. {text}** ✓ Correct")
            elif opt == user_ans and user_ans != correct:
                st.error(f"{opt}. {text} ✗ Your answer")
            else:
                st.write(f"{opt}. {text}")

        st.info(f"💡 {q['explanation']}")
        st.divider()

        if idx + 1 < total:
            if st.button("Next question →", type="primary"):
                st.session_state["current_q"] += 1
                st.rerun()
        else:
            if st.button("See Results 🏁", type="primary"):
                save_session(
                    user_id             = st.session_state["user_id"],
                    email               = user["email"],
                    display_name        = user["display_name"],
                    topics              = st.session_state["selected_topics"],
                    difficulty          = st.session_state["difficulty"],
                    num_questions       = total,
                    score               = st.session_state["score"],
                    show_on_leaderboard = st.session_state.get("show_on_leaderboard", True),
                )
                st.session_state["quiz_done"] = True
                st.rerun()


# ═══════════════════════════════════════════════════════════════
# PAGE: My History  (registered users only)
# ═══════════════════════════════════════════════════════════════
elif page == "My History":
    import pandas as pd

    st.title("My Quiz History")
    history = fetch_user_history(user["email"])

    if not history:
        st.info("You haven't completed any quizzes yet. Start one from the Quiz tab!")
    else:
        df = pd.DataFrame(history)
        df["topics"] = df["topics"].apply(lambda t: ", ".join(t) if isinstance(t, list) else t)
        df["completed_at"] = pd.to_datetime(df["completed_at"]).dt.strftime("%Y-%m-%d %H:%M")
        df.columns = ["Difficulty", "Questions", "Score", "Score %", "Topics", "Date"]
        st.dataframe(df, use_container_width=True, hide_index=True)


# ═══════════════════════════════════════════════════════════════
# PAGE: Leaderboard
# ═══════════════════════════════════════════════════════════════
elif page == "Leaderboard":
    import pandas as pd

    st.title("🏆 Leaderboard")
    board = fetch_leaderboard(50)

    if not board:
        st.info("No scores yet — be the first to finish a quiz!")
    else:
        df = pd.DataFrame(board)
        df["topics"] = df["topics"].apply(lambda t: ", ".join(t) if isinstance(t, list) else t)
        df["completed_at"] = pd.to_datetime(df["completed_at"]).dt.strftime("%Y-%m-%d %H:%M")
        df.insert(0, "Rank", range(1, len(df) + 1))
        df.columns = ["Rank", "Name", "Difficulty", "Questions",
                      "Score", "Score %", "Topics", "Date"]
        st.dataframe(df, use_container_width=True, hide_index=True)
