import streamlit as st
from db import save_session, fetch_leaderboard, test_connection
from question_gen import get_questions, generate_weakness_report

st.set_page_config(
    page_title="Data Engineering Quiz",
    page_icon="🛢️",
    layout="centered",
)

TOPICS = [
    "SQL", "Snowflake", "dbt", "Apache Spark", "Databricks",
    "Data Modeling", "ELT/ETL", "Python", "Cloud Storage",
]
DIFFICULTIES = ["Easy", "Medium", "Hard"]


# ── Connection check ─────────────────────────────────────────
if "sf_ok" not in st.session_state:
    st.session_state["sf_ok"] = False
    st.session_state["sf_err"] = ""
    try:
        ok, err = test_connection()
        st.session_state["sf_ok"] = ok
        st.session_state["sf_err"] = err
    except Exception as e:
        st.session_state["sf_err"] = str(e)

if not st.session_state["sf_ok"]:
    st.title("🛢️ Data Engineering Quiz")
    st.error("The service is temporarily unavailable. Please try again later.")
    if st.button("Retry"):
        st.session_state.pop("sf_ok", None)
        st.cache_resource.clear()
        st.rerun()
    st.stop()


# ── Sidebar ──────────────────────────────────────────────────
with st.sidebar:
    st.title("🛢️ DE Quiz")
    if "user" in st.session_state:
        st.write(f"**{st.session_state['user']['display_name']}**")
        if st.button("Change name"):
            st.session_state.pop("user", None)
            for key in ["questions", "current_q", "answers", "score",
                        "quiz_done", "selected_topics", "difficulty",
                        "num_questions", "show_on_leaderboard"]:
                st.session_state.pop(key, None)
            st.rerun()
        st.divider()
        page = st.radio("Navigate", ["Quiz", "Leaderboard"])
    else:
        page = "home"


# ── Helper ───────────────────────────────────────────────────
def reset_quiz():
    for key in ["questions", "current_q", "answers", "score",
                "quiz_done", "selected_topics", "difficulty",
                "num_questions", "show_on_leaderboard"]:
        st.session_state.pop(key, None)


# ═══════════════════════════════════════════════════════════════
# PAGE: Landing — enter name
# ═══════════════════════════════════════════════════════════════
if "user" not in st.session_state:
    st.title("🛢️ Data Engineering Quiz")
    st.markdown(
        "Test your knowledge across SQL, Snowflake, dbt, Spark, Databricks, "
        "Data Modeling, ELT/ETL, Python, and Cloud Storage.\n\n"
        "Questions are AI-generated by **Snowflake Cortex** and adapt to your chosen difficulty."
    )
    st.divider()

    with st.form("name_form"):
        name = st.text_input("Enter your name to begin", placeholder="Your name")
        submitted = st.form_submit_button("Let's go →", type="primary",
                                          use_container_width=True)
        if submitted:
            st.session_state["user"] = {
                "display_name": name.strip() or "Anonymous",
                "email":        f"user_{name.strip().lower().replace(' ', '_')}",
            }
            st.rerun()
    st.stop()


# ═══════════════════════════════════════════════════════════════
# PAGE: Quiz
# ═══════════════════════════════════════════════════════════════
if page == "Quiz":

    if "questions" not in st.session_state:
        st.title("New Quiz")

        selected_topics = st.multiselect(
            "Select topics (pick at least one)",
            TOPICS,
            default=["SQL", "Snowflake"],
        )
        col1, col2 = st.columns(2)
        with col1:
            difficulty = st.selectbox("Difficulty", DIFFICULTIES)
        with col2:
            num_questions = st.selectbox("Number of questions", [10, 20])

        st.divider()
        show_on_leaderboard = st.checkbox(
            "Add my score to the public leaderboard", value=True
        )

        if st.button("Start Quiz 🚀", type="primary", use_container_width=True,
                     disabled=len(selected_topics) == 0):
            with st.spinner("Generating your quiz… this may take ~20 seconds on first run."):
                questions = get_questions(selected_topics, difficulty, num_questions)

            if not questions:
                st.error("Could not generate questions. Please try again.")
                st.stop()

            st.session_state.update({
                "questions":           questions,
                "current_q":           0,
                "answers":             {},
                "score":               0,
                "quiz_done":           False,
                "selected_topics":     selected_topics,
                "difficulty":          difficulty,
                "num_questions":       num_questions,
                "show_on_leaderboard": show_on_leaderboard,
            })
            st.rerun()
        st.stop()

    # ── Results screen ────────────────────────────────────────
    if st.session_state.get("quiz_done"):
        questions = st.session_state["questions"]
        score     = st.session_state["score"]
        total     = len(questions)
        pct       = round(score / total * 100)

        st.title("Results")
        col1, col2, col3 = st.columns(3)
        col1.metric("Score", f"{score}/{total}")
        col2.metric("Percentage", f"{pct}%")
        col3.metric("Difficulty", st.session_state["difficulty"])

        if pct >= 80:
            st.success("Excellent work! 🏆")
        elif pct >= 60:
            st.info("Good effort! Keep practising. 💪")
        else:
            st.warning("Keep studying — you'll get there! 📚")

        st.divider()
        with st.spinner("Generating your personalised feedback..."):
            report = generate_weakness_report(
                questions  = questions,
                answers    = st.session_state["answers"],
                topics     = st.session_state["selected_topics"],
                difficulty = st.session_state["difficulty"],
            )
        if report:
            st.subheader("Coach Feedback")
            st.info(report)

        st.divider()
        st.subheader("Review")
        for i, q in enumerate(questions):
            user_ans = st.session_state["answers"].get(i)
            correct  = q["correct_option"]
            icon     = "✅" if user_ans == correct else "❌"
            with st.expander(f"{icon} Q{i+1}: {q['question_text']}"):
                for opt in ["A", "B", "C", "D"]:
                    text = q[f"option_{opt.lower()}"]
                    if opt == correct:
                        st.markdown(f"**{opt}. {text}** ✓")
                    elif opt == user_ans:
                        st.markdown(f"~~{opt}. {text}~~ ✗")
                    else:
                        st.markdown(f"{opt}. {text}")
                st.info(f"**Explanation:** {q['explanation']}")

        st.divider()
        if st.button("Take another quiz", use_container_width=True):
            reset_quiz()
            st.rerun()
        st.stop()

    # ── Active question ───────────────────────────────────────
    questions = st.session_state["questions"]
    idx       = st.session_state["current_q"]
    total     = len(questions)
    q         = questions[idx]

    st.progress(idx / total, text=f"Question {idx+1} of {total}")
    st.subheader(f"Q{idx+1}. {q['question_text']}")

    already_answered = idx in st.session_state["answers"]

    if not already_answered:
        choice = st.radio(
            "Choose your answer:",
            ["A", "B", "C", "D"],
            format_func=lambda x: f"{x}. {q[f'option_{x.lower()}']}",
            key=f"radio_{idx}",
        )
        if st.button("Submit", type="primary"):
            st.session_state["answers"][idx] = choice
            if choice == q["correct_option"]:
                st.session_state["score"] += 1
            st.rerun()
    else:
        user_ans = st.session_state["answers"][idx]
        correct  = q["correct_option"]
        for opt in ["A", "B", "C", "D"]:
            text = q[f"option_{opt.lower()}"]
            if opt == correct:
                st.success(f"**{opt}. {text}** ✓ Correct")
            elif opt == user_ans and user_ans != correct:
                st.error(f"{opt}. {text} ✗ Your answer")
            else:
                st.write(f"{opt}. {text}")

        st.info(f"💡 {q['explanation']}")
        st.divider()

        if idx + 1 < total:
            if st.button("Next question →", type="primary"):
                st.session_state["current_q"] += 1
                st.rerun()
        else:
            if st.button("See Results 🏁", type="primary"):
                user = st.session_state["user"]
                save_session(
                    user_id             = None,
                    email               = user["email"],
                    display_name        = user["display_name"],
                    topics              = st.session_state["selected_topics"],
                    difficulty          = st.session_state["difficulty"],
                    num_questions       = total,
                    score               = st.session_state["score"],
                    show_on_leaderboard = st.session_state.get("show_on_leaderboard", True),
                )
                st.session_state["quiz_done"] = True
                st.rerun()


# ═══════════════════════════════════════════════════════════════
# PAGE: Leaderboard
# ═══════════════════════════════════════════════════════════════
elif page == "Leaderboard":
    import pandas as pd

    st.title("🏆 Leaderboard")
    board = fetch_leaderboard(50)

    if not board:
        st.info("No scores yet — be the first to finish a quiz!")
    else:
        df = pd.DataFrame(board)
        df["topics"] = df["topics"].apply(
            lambda t: ", ".join(t) if isinstance(t, list) else t
        )
        df["completed_at"] = pd.to_datetime(df["completed_at"]).dt.strftime("%Y-%m-%d %H:%M")
        df.insert(0, "Rank", range(1, len(df) + 1))
        df.columns = ["Rank", "Name", "Difficulty", "Questions",
                      "Score", "Score %", "Topics", "Date"]
        st.dataframe(df, use_container_width=True, hide_index=True)
